### ISSUE TITLE
generate hash command

### ISSUE THREAD

**Issue by ArtifactyNight** [SamB440/ForcePack#2]
Add command to auto generate hash to config like `/forcepack genhash`
this feature is useful for upload resourcepack but same direct url

**Comment by SamB440** [comment]
/forcepack reload will already make the resource pack generate the hash though?

**Comment by SamB440** [comment]
> > /forcepack reload will already make the plugin generate the hash though?
> 
> is this work with velocity too?

Yes, on velocity it's /forcepackreload. Basically does the same thing, where it initiates a total reload of resource packs as if the plugin was just starting up.
