### ISSUE TITLE
1.17+ custom resource pack message does not work

### ISSUE THREAD

**Issue by marlester-dev** [SamB440/ForcePack#21]
just look at this
![Снимыыок](https://user-images.githubusercontent.com/77095872/221365558-7f5a95ad-68a2-4bf3-9db3-c290d325888e.JPG)
There is no difference beetwen normal one and so players will just deny it
my server version is 1.17.1 git-Paper-"2826b44"

**Comment by SamB440** [comment]
1.17 doesn't support this, no API

**Comment by SamB440** [comment]
> > 1.17 doesn't support this, no API
> 
> dude then why is it 1.17+ ? I can't even set custom message for these 'Yes' and 'No' buttons, there is just no difference

Because 1.17 clients support it. 

And no, you can't set a custom yes/no button message, because those are client sided.

**Comment by SamB440** [comment]
The other plugin uses NMS and hackery to do things. I don't want to do that. It's not worth my time to support a single feature on a single version.

**Comment by SamB440** [comment]
> > The other plugin uses NMS and hackery to do things. I don't want to do that. It's not worth my time to support a single feature on a single version.
> 
> Ok, but then you should say about this nuance in plugin description or somewhere in faq because I didn't notice that in description and didn't find answer in faq

I've specifically said on the plugin description that it's for 1.17+ *clients*, if you run a e.g 1.19 server with viabackwards it will work for 1.17 clients (I believe).
