### ISSUE TITLE
Kick message

### ISSUE THREAD

**Issue by LeCraft2Ouf** [SamB440/ForcePack#22]
Bonjour j'ai cette raison quand je refuse le pack de texture :

![image](https://user-images.githubusercontent.com/29964590/224579632-da6b7754-e021-4465-a770-28b89cf5a51d.png)

Au lieu d'y avoir ce message : "Vous devez accepter le resource pack pour jouer sur notre serveur. Vous ne savez pas comment faire ? Consultez le site &ehttps://samb440.gitlab.io/resourcepack.html."

Dernière version de votre plugin, sous Paper 1.18.2, MC 1.18.2.

Merci de votre réponse.

**Comment by SamB440** [comment]
Unfortunately that message cannot be changed. It is client-sided.
