### ISSUE TITLE
Need help with Server Resource Pack must set to Prompt in server edit in order to join

### ISSUE THREAD

**Issue by Xyio24** [SamB440/ForcePack#26]
Hi, i get this error in the console that says:

> [12:25:46 INFO]:[ForcePack] Using 1.18 method
> [12:25:46 INFO]: [ForcePack] Xyio24_'s exemptions: geyser, false. permission, false.
> [12:25:46 INFO]: [ForcePack] Xyio24_ sent status: ACCEPTED
> [12:25:46 INFO]: [ForcePack] Kicked player Xyio24_ because they are sending fake resource pack statuses (accepted sent twice).

The problem is if the texturepack is enabled, then the player will get kicked. however if it is set to prompt then the player can enter the server normally. Sorry for bad english

> Server version: git-Purpur-1976 (MC: 1.19.4)*
> Java 18
> ForcePack versin 1.2.9 #

**Comment by SamB440** [comment]
As it says, you accepted the resource pack twice somehow, so you have another plugin sending a pack or one set in server.properties
