### ISSUE TITLE
Distribution on non-Spigot sites

### ISSUE THREAD

**Issue by pontaoski** [SamB440/ForcePack#28]
Spigot's website is kinda a PITA to build deploying automations around due to the fact that it only wants you to use it interactively. Could we get distribution on e.g. Modrinth or Hangar? This would make consuming ForcePack in automated environments much easier.

**Comment by SamB440** [comment]
I have submitted the project to Modrinth, waiting for approval then 1.3.0 will be published on Spigot as well.

I might do Hangar in the future.
