### ISSUE TITLE
ForcePack Your URL has an invalid or unknown format.

### ISSUE THREAD

**Issue by Nanichan20** [SamB440/ForcePack#33]
idk if this is a my issue or not but i've done everything correctly i presumed and since this is pretty much the first time i set this plugin up 
i am not sure if i've done something wrong, but here's what i've done so far

the link to the screenshot at imgur: https://imgur.com/a/slqst6R

**Comment by SamB440** [comment]
Yes, Dropbox has changed their URL format. I need to update it.

**Comment by Nanichan20** [comment]
Any otherway i can make use of the plugin right now, give me a recommendation if you got any

**Comment by SamB440** [comment]
You don't need to change anything, the plugin will work anyway.

**Comment by SamB440** [comment]
Fixed in 73a7d339c577d7d1f2f06c10106022cbbea13d37
