### ISSUE TITLE
Error "You must accept the resource pack"

### ISSUE THREAD

**Issue by Itras500** [SamB440/ForcePack#35]
Hello,

I am currently trying to use Force Pack on my 1.18.2 Paper Server. However, all players are always kicked from the server because the resource pack was allegedly not accepted. I always get the following message in the console.

![image](https://github.com/SamB440/ForcePack/assets/24420846/e5320cf8-9480-402b-8e82-25d4ff24bce2)

In Minecraft I always get the following message.

![image](https://github.com/SamB440/ForcePack/assets/24420846/28f6b630-9645-4976-94e4-b4b14d2654e4)

The settings for server resource packs in my client are also set to enabled. 

I am also attaching my config.yml here once again. I have already successfully tested the URL and the hash. Everything should be correct here.

![image](https://github.com/SamB440/ForcePack/assets/24420846/79786a0e-fbea-4e2d-9d5a-52579dcc2f47)

**Comment by SamB440** [comment]
> Hello,
> 
> I am currently trying to use Force Pack on my 1.18.2 Paper Server. However, all players are always kicked from the server because the resource pack was allegedly not accepted. I always get the following message in the console.
> 
> ![image](https://user-images.githubusercontent.com/24420846/265259363-e5320cf8-9480-402b-8e82-25d4ff24bce2.png)
> 
> In Minecraft I always get the following message.
> 
> ![image](https://user-images.githubusercontent.com/24420846/265259404-28f6b630-9645-4976-94e4-b4b14d2654e4.png)
> 
> The settings for server resource packs in my client are also set to enabled.
> 
> I am also attaching my config.yml here once again. I have already successfully tested the URL and the hash. Everything should be correct here.
> 
> ![image](https://user-images.githubusercontent.com/24420846/265259536-79786a0e-fbea-4e2d-9d5a-52579dcc2f47.png)

They are sending an accept status twice, which is impossible

**Comment by Itras500** [comment]
Sorry, I could have thought of that myself. But maybe the information will help if someone comes up with it again.

Apparently it sends it twice if the server.properties still contains the information about the resource pack. I have now deleted everything from the file so that only the Force Pack config still contains the information about the Resource Pack. Then it works! I know, it's also in the instructions, my mistake.

In any case, thanks for the handy plugin!

**Comment by SamB440** [comment]
I should probably add some kind of detection for people leaving stuff in server.properties in the future.
