### ISSUE TITLE
Imposible to connect in server without Viarewind

### ISSUE THREAD

**Issue by JunkieCraft** [SamB440/ForcePack#4]
I have been observing and it is impossible to enter the server without having the viarewind plugin. According to indications it is necessary to have Viaversion, but not viarewind.

Every time I try to log in to the server it always says: Failed to download the resourcepack.

Pugin version: 1.2.2
Minecraft server version: 1.18.2

**Comment by SamB440** [comment]
ViaVersion is not a required plugin, it's an optional dependency for older client support. 

I've been using ForcePack with ViaVersion for a while on both proxy and backend server. What client version are you trying to use? Is your server a proxy or backend server?

**Comment by JunkieCraft** [comment]
The problem is using forcepack without viarewind , when I'm trying enter yo server without viarewind, It says that the pack can't be downloaded.

I'm using 1.18.2 server version and same for client

**Comment by SamB440** [comment]
Please provide an example config so I can attempt to reproduce this

**Comment by JunkieCraft** [comment]
Hello Sam! nvm solved! Was a problem with other plugin that also use a resourcepack

Thanks for all! :)
