### ISSUE TITLE
Resource pack applied detection not working

### ISSUE THREAD

**Issue by fibberclip** [SamB440/ForcePack#42]
I'm having an issue where having the prevent movement and damage options enabled is not allowing players to move or take damage at all even if the resource pack has already been accepted and applied. I thought at first it was bc i had Server Resource Packs to "Enable" Instead of "Prompt" in the game config, but even after setting it to Prompt and accepting the prompt, after the pack is applied it continues to prevent movement and damage. I de-op'd myself too to make sure that wasn't causing any issues, and the server.properties file has no configs on the resource pack options. I have a plugin that plays a sound everytime a player joins (ConditionalEvents) but that shouldn't be the issue since it doesn't teleport, the prompt shows up and the pack applies with no issues. Debug after accepting the prompt shows a message saying "Using 1.18 method", and then it only shows the "Cancelled movement for player 'player' due to resource pack not applied." message, doesn't show anything abt the pack being accepted, applied, nothing.
Plus, i started getting an issue where every time i exit the server, i get an "Resource reload failed" error which de-applies all my personally set resource packs, which wasn't happening at all until now.

I'm playing on 1.18.2, any way to fix it and keep the options enabled or is it better to just disable them?

**Comment by SamB440** [comment]
Since there was no message about the pack being accepted, the server is not receiving a response from the client.

1. Are you on a fully vanilla client?
2. Is the server behind a proxy?

**Comment by fibberclip** [comment]
I forgot to mention it but no, i'm on Magma 1.18.2 so running with Forge mods, that's the only thing that's failing, cuz on the client side the resource pack seems to work fine until i leave the server and get the reload error.

As far as i know, no, it isn't
