### ISSUE TITLE
Error on join

### ISSUE THREAD

**Issue by VictimOfPing** [SamB440/ForcePack#58]
when I try to enter the mode it gives me this error:

![image](https://github.com/SamB440/ForcePack/assets/120317607/0cd66f2a-2300-4fc7-8607-5767ee715aaf)

**Comment by SamB440** [comment]
It should be fixed in the latest dev build, please try that. Although the GitHub CI seems to have ran on the wrong commit.

[libs.zip](https://github.com/SamB440/ForcePack/files/14302055/libs.zip)

**Comment by VictimOfPing** [comment]
I am already using the latest version

**Comment by VictimOfPing** [comment]
oh ok ty
