### ISSUE TITLE
Couldn't pass ServerPostConnectEvent to forcepack

### ISSUE THREAD

**Issue by JonahTheEngi1** [SamB440/ForcePack#60]
Getting this error on every connect and the prompt for pack not appearing. 

Here is my config 

`
geyser = false
verify-resource-packs = true
update-gui = true
update-gui-speed = 1000
force-invalid-size = false
force-constant-download = true
disable-commands-until-loaded = false
exclude-commands = [
   "exampleone",
   "exampletwo",
]
bypass-permission = false
enable-mc-164316-fix = true
use-new-force-pack-screen = true
try-to-stop-fake-accept-hacks = true
delay-pack-sending-by = 0

debug = false
[web-server]
    enabled = false
    server-ip = "localhost"
    port = 27010

[unload-pack]
    enable = false
    url = "https://download.mc-packs.net/pack/10beb398d88eee64fda1f1b0227f9159a0153e74.zip"
    hash = "10beb398d88eee64fda1f1b0227f9159a0153e74"
    generate-hash = false
    exclude = [
        "exampleserver"
    ]

[global-pack]
    enable = true
    url = "https://download.mc-packs.net/pack/10beb398d88eee64fda1f1b0227f9159a0153e74.zip"
    hash = "10beb398d88eee64fda1f1b0227f9159a0153e74"
    generate-hash = false
    resourcepack.prompt = "<yellow>Please accept our resource pack to improve your experience."
    exclude = [
        "exampleserver"
    ]

    [global-pack.actions]
        [global-pack.actions.ACCEPTED]
            kick = false
            commands = []
        [global-pack.actions.DECLINED]
            kick = true
            message = "<color:#FF5555>Please accept our resource pack to play on the server!"
            commands = []
        [global-pack.actions.FAILED_DOWNLOAD]
            kick = true
            message = "<color:#FF5555>The resource pack download failed. Please try rejoining."
            commands = []
        [global-pack.actions.FAILED_RELOAD]
            kick = true
            message = "<color:#FF5555>The resource pack reload failed. Please try rejoining."
            commands = []
        [global-pack.actions.SUCCESSFUL]
            kick = false
            commands = []

[groups]
    [groups.example-group]
        exact-match = true
        servers = [
            "hub01",
            "enviroment01",
            "jungleplanet"
        ]
        resourcepack.url = "https://download.mc-packs.net/pack/10beb398d88eee64fda1f1b0227f9159a0153e74.zip"
        resourcepack.generate-hash = false
        resourcepack.hash = "10beb398d88eee64fda1f1b0227f9159a0153e74"
        resourcepack.prompt = "<yellow>Please accept our resource pack to improve your experience."
        [groups.example-group.actions]
            [groups.example-group.actions.ACCEPTED]
                kick = false
                commands = []
            [groups.example-group.actions.DECLINED]
                kick = true
                message = "<color:#FF5555>Please accept our resource pack to play on the server!"
                commands = []
            [groups.example-group.actions.FAILED_DOWNLOAD]
                kick = true
                message = "<color:#FF5555>The resource pack download failed. Please try rejoining."
                commands = []
            [groups.example-group.actions.FAILED_RELOAD]
                kick = true
                message = "<color:#FF5555>The resource pack reload failed. Please try rejoining."
                commands = []
            [groups.example-group.actions.SUCCESSFUL]
                kick = false
                commands = []

[servers]
    [servers.example-server]
        resourcepack.urls = ["https://www.convallyria.com/files/BlankPack.zip"]
        resourcepack.generate-hash = false
        resourcepack.hashes = ["118AFFFC54CDCD308702F81BA24E03223F15FE5F"]
        resourcepack.prompt = "<yellow>Please accept our resource pack to improve your experience."
        [servers.example-server.actions]
            [servers.example-server.actions.ACCEPTED]
                kick = false
                commands = []
            [servers.example-server.actions.DECLINED]
                kick = true
                message = "<color:#FF5555>Please accept our resource pack to play on the server!"
                commands = []
            [servers.example-server.actions.FAILED_DOWNLOAD]
                kick = true
                message = "<color:#FF5555>The ResourcePack download failed. Please try rejoining."
                commands = []
            [servers.example-server.actions.FAILED_RELOAD]
                kick = true
                message = "<color:#FF5555>The resource pack reload failed. Please try rejoining."
                commands = []
            [servers.example-server.actions.SUCCESSFUL]
                kick = false
                commands = []
`

and here is the error 
`[07:08:38 ERROR]: Couldn't pass ServerPostConnectEvent to forcepack
java.lang.NoSuchFieldError: MINECRAFT_1_20_3
        at com.convallyria.forcepack.velocity.handler.PackHandler.lambda$setPack$9(PackHandler.java:98) ~[?:?]
        at java.util.Optional.ifPresentOrElse(Optional.java:196) ~[?:?]
        at com.convallyria.forcepack.velocity.handler.PackHandler.setPack(PackHandler.java:96) ~[?:?]
        at com.convallyria.forcepack.velocity.listener.ResourcePackListener.onJoin(ResourcePackListener.java:174) ~[?:?]
        at com.convallyria.forcepack.velocity.listener.Lmbda$26.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:597) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:478) ~[velocity.jar:3.2.0-SNAPSHOT (git-8dcc7ee3-b294)]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:840) [?:?]`

**Comment by SamB440** [comment]
Outdated velocity version.
