### ISSUE TITLE
Resource pack doesn't load after switching to a server which does not have resource pack

### ISSUE THREAD

**Issue by MatinHQ** [SamB440/ForcePack#62]
Hello I am using velocity 3.3.0 build 360 and there is a issue with loading resource pack on server switch I described the issue in video below

https://mega.nz/file/E7xH2DKI#egDyHLUn_Yhnh4jKtgZQUeGLI6NozIUvofz2zquBvtM

**Comment by SamB440** [comment]
Have you tried the latest commit? https://github.com/SamB440/ForcePack/actions/runs/7892224966/artifacts/1242736566

**Comment by MatinHQ** [comment]
Not sure it was just latest download from spigot I will try this out

**Comment by MatinHQ** [comment]
> ctions/runs/7892224966/artifacts/1242736566

tested that and it's same

**Comment by SamB440** [comment]
I would need debug output when it occurs

**Comment by MatinHQ** [comment]
Just updated velocity to latest, build 370 and it fixed

**Comment by SamB440** [comment]
Good to hear, although I only see changes to backend forwarding so I'm not sure what would have fixed it.
