### ISSUE TITLE
1.21 Support or plugin abandoned?

### ISSUE THREAD

**Issue by Humithear** [SamB440/ForcePack#72]
Been too long, all plugins are updated and this feels like its abandoned, because all that was said ''will do soon'' because demotivated with an unrelated problem that doesnt affect updating.

Will we atleast get a true ETA / Fix or just honest answer that the plugin will be abandoned so we pay for others?

**Comment by SamB440** [comment]
"All plugins are updated" is not true, many are still struggling with the 1.21 update, I help maintain Grim for instance and it still barely supports 1.21, I spent over a week with others updating that to new step movement logic and another week working on an attribute rewrite.

**Comment by SamB440** [comment]
Update to 1.3.5.
