### ISSUE TITLE
message send by [Server] still if didn`t set Command:

### ISSUE THREAD

**Issue by lonlf** [SamB440/ForcePack#78]
I installed the plugin both Paper and Velocity.

In Paper plugins/ForcePack/config.yml

### If ->  
SUCCESSFULLY_LOADED.kick: false.Commands:  or Commands: #- say [player] successfully loaded the resource pack!
->
it send: [Server] xxx successfully loaded the resource pack!

**Comment by SamB440** [comment]
It's meant to be set to `Commands: []` to disable them
